### ISSUE TITLE
Problem running on Raspberry Pi 3 & Fedora 32

### ISSUE THREAD

**Issue by jcollie** [abcminiuser/python-homeassistant-streamdeck#7]
I'm having a problem running this on a Rasberry Pi 3. Works just fine on my desktop system. They are both running Fedora 32.

```
[root@streamdeck01 src]# /opt/streamdeck/bin/python HassClient.py 
INFO:root:Reading config file "config.yaml"...
INFO:root:Debug enabled
INFO:root:Connecting to xxxxxxxxxx:443...
WARNING:asyncio:Executing <Task finished name='Task-1' coro=<main() done, defined at HassClient.py:91> exception=TransportError('Failed to write out report (-1)') created at /usr/lib64/python3.8/asyncio/base_events.py:595> took 1.003 seconds
Traceback (most recent call last):
  File "HassClient.py", line 183, in <module>
    init_ok = loop.run_until_complete(main(loop, config))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "HassClient.py", line 160, in main
    deck.open()
  File "/opt/streamdeck/lib64/python3.8/site-packages/StreamDeck/Devices/StreamDeck.py", line 129, in open
    self._reset_key_stream()
  File "/opt/streamdeck/lib64/python3.8/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 97, in _reset_key_stream
    self.device.write(payload)
  File "/opt/streamdeck/lib64/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 376, in write
    return self.hidapi.write(self.device_handle, payload)
  File "/opt/streamdeck/lib64/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 246, in write
    raise TransportError("Failed to write out report (%d)" % result)
StreamDeck.Transport.Transport.TransportError: Failed to write out report (-1)
python: io.c:2146: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.
Aborted (core dumped)
```

**Comment by abcminiuser** [comment]
Can you try with the latest `streamdeck` version (0.8.1) please? This might be related to some transport fixes I've made in the last week.
