### ISSUE TITLE
Could not open HID device, Debian Buster and Raspberry Pi Model B

### ISSUE THREAD

**Issue by rontus** [abcminiuser/python-homeassistant-streamdeck#8]
Trying the program immediately hangs to this error: "StreamDeck.Transport.Transport.TransportError: Could not open HID device."

I have installed libhidapi-libusb0 from apt to get it even that far.

Any pointers for me to fix this or is it something with the software?

$ python3 HassClient.py
INFO:root:Reading config file "config.yaml"...
INFO:root:Connecting to myservername.duckdns.org:8123...
Traceback (most recent call last):
  File "HassClient.py", line 183, in <module>
    init_ok = loop.run_until_complete(main(loop, config))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "HassClient.py", line 160, in main
    deck.open()
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 334, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/pi/.local/lib/python3.7/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 178, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.

**Comment by rontus** [comment]
Figured it out, it's working now.
I needed to run the program with sudo (and install the pip3 packages with sudo too.).

Now will just face the challenges of figuring out the configuration.yaml to my preferences ;)
